name: Coverage

on: 
  pull_request:
    branches: main
    paths-ignore:
      - ".changeset/**"
      - ".vscode/**"
      - "CHANGELOG.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Test coverage
        run: pnpm test:coverage

      - name: Report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2.8.1


